#!/bin/sh
# Salir inmediatamente si un comando falla.
set -e

echo "Recargando demonio de Systemd..."
systemctl daemon-reload

# Habilitar el servicio para que se inicie en el arranque.
# La condición 'if' asegura que esto solo ocurra en la instalación inicial,
# no en las actualizaciones.
if [ "$1" = "configure" ]; then
    echo "Habilitando el servicio ghostknockd..."
    systemctl enable ghostknockd.service
fi

exit 0
